platform :ios, '10.0'
project 'FilmesOnline.xcodeproj'

target 'FilmesOnline' do
    use_frameworks!

    pod 'Alamofire', '~> 5.0.0-rc.2'
    pod 'SwiftyJSON', '~> 4.3.0'
    pod 'AlamofireImage', '~> 4.0.0-beta.5'

end
