platform :ios, '10.0'
project 'FilmesOnlineMVVM.xcodeproj'

target 'FilmesOnlineMVVM' do
    use_frameworks!

    pod 'Alamofire', '~> 5.0.0-rc.2'
    pod 'SwiftyJSON', '~> 4.3.0'
    pod 'AlamofireImage', '~> 4.0.0-beta.5'
    pod 'RxSwift', '~> 5.0.0'
    pod 'RxRelay', '~> 5.0.0'

end
